using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GTA_5_Mission_Creator_Tool.Models
{
	enum Natives : uint
	{
		// Player
		PLAYER_IS_PLAYER_ONLINE = 0x396D00,
		
		// Network
		NETWORK_PLAYER_IS_ROCKSTAR_DEV = 0x39BC34,
		NETWORK_UGC_HAS_MODIFY_FINISHED = 0x3A14B8,
		NETWORK_IS_CLOUD_AVAILABLE = 0x396D48,

		// Gameplay
		GAMEPLAY_SET_SAVE_MENU_ACTIVE = 0x38CC9C,
		GAMEPLAY_TERMINATE_ALL_SCRIPTS_WITH_THIS_NAME = 0x38CDDC,

		// Datafile
		DATAFILE_UGC_CREATE_CONTENT = 0x374760,
		DATAFILE_UPDATE_SAVE_TO_CLOUD = 0x375228,
		DATAFILE_GET_FILE_DICT = 0x3752F0,
		OBJECT_STRINGIFY = 0x37460C,
		OBJECT_VALUE_ADD_INTEGER = 0x375324,

		// SYstem
		SYSTEM_START_NEW_SCRIPT = 0x91FB74,

		// Script
		SCRIPT_REQUEST_SCRIPT = 0x407184,
		SCRIPT_HAS_SCRIPT_LOADED = 0x4072B4,
		SCRIPT_DOES_SCRIPT_EXIST = 0x40735C,
		SCRIPT_SET_SCRIPT_AS_NO_LONGER_NEEDED = 0x407228,
		SCRIPT_GET_NUMBER_OF_REFERENCES_OF_SCRIPT_WITH_NAME_HASH = 0x3E1528
	}
}
